#!/usr/bin/env bash

set -e

SPOTIFY_CLIENT_ID=$1
SPOTIFY_CLIENT_SECRET=$2
SPOTIFY_ARTIST_IDS=$3

echo #@


if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <client_id> <client_secret> <artist_ids>"
    echo "Artist ids should bie given in the form 'abcd;efgh;ijkl"
    exit 1
fi

access_token=$(source ./login "$SPOTIFY_CLIENT_ID" "$SPOTIFY_CLIENT_SECRET")
echo "Login successful"
IFS=';' read -ra artists <<< "$SPOTIFY_ARTIST_IDS"

rm -rf data
mkdir data

echo "Retrieving details for ${#SPOTIFY_ARTIST_IDS[@]} artists"

for artist in "${artists[@]}"; do
    mkdir "data/$artist"
    echo "Getting details for id $artist"
    artist_details=$(source ./artist "$access_token" "$artist")
    artist_name=$(echo "$artist_details" | jq -r .name)
    echo "Artist is: $artist_name"
    albums=$(source ./albums "$access_token" "$artist")
    echo "Albums retrieved successfully"

    cat <<< "${artist_details}" > "data/${artist}/artist"
    cat <<< "${albums}" > "data/${artist}/albums"
done

cat <<< "${SPOTIFY_ARTIST_IDS}" > "data/artists"

